export const SESSION_STORAGE_COLLECTION_DETAILS_KEY = "123NFTCollectionDetails";
export const SESSION_STORAGE_PROJECT_STRUCTURE_KEY = "123NFTProjectStructure";
export const DEFAULT_TOTAL_IMAGES = 1000;
export const SESSION_STORAGE_URL_KEY = "123NFTURLKey";
